import type { DocumentSchema } from './types';

// Phase 0 hardcoded schema: a slice of the Navion Client Policy Fact Sheet.
// Exercises every architectural pattern: header band, logo, static text,
// dividers, two text fields, and a 3-column policy row with date highlighting.
export const navionSample: DocumentSchema = {
  id: 'doc_navion_phase0',
  version: 1,
  meta: {
    title: 'Client Policy Fact Sheet & Summary',
    pageSize: { w: 612, h: 792 },
    units: 'pt',
    margins: { top: 36, right: 36, bottom: 36, left: 36 },
  },
  theme: {
    colors: {
      primary: '#1B2A6B',
      accent: '#C9A227',
      fieldBg: '#EEF2F9',
      fieldBorder: '#D5DEEC',
      attentionBg: '#FBF4DD',
      white: '#FFFFFF',
    },
    fonts: {
      heading: { family: 'Poppins' },
      body: { family: 'Inter' },
    },
  },
  pages: [
    {
      id: 'page_1',
      elements: [
        // ── HEADER BAND ─────────────────────────────────────────────
        {
          id: 'el_header_bg',
          type: 'rect',
          x: 36, y: 36, w: 540, h: 68,
          fill: '#1B2A6B',
          radius: 8,
        },
        // Logo placeholder (white box inside header)
        {
          id: 'el_logo_bg',
          type: 'rect',
          x: 50, y: 46, w: 100, h: 48,
          fill: '#FFFFFF',
          radius: 4,
        },
        {
          id: 'el_logo_text',
          type: 'text',
          x: 50, y: 58, w: 100, h: 24,
          content: 'NAVION',
          fontRef: 'heading',
          size: 13,
          color: '#1B2A6B',
          align: 'center',
          weight: 'bold',
        },
        {
          id: 'el_logo_sub',
          type: 'text',
          x: 50, y: 74, w: 100, h: 14,
          content: 'INSURANCE',
          fontRef: 'body',
          size: 7,
          color: '#4B6CB7',
          align: 'center',
        },
        // Title text (right of logo, inside header)
        {
          id: 'el_title',
          type: 'text',
          x: 164, y: 51, w: 398, h: 22,
          content: 'Client Policy Fact Sheet & Summary',
          fontRef: 'heading',
          size: 15,
          color: '#FFFFFF',
          align: 'left',
          weight: 'bold',
        },
        {
          id: 'el_subtitle',
          type: 'text',
          x: 164, y: 75, w: 398, h: 16,
          content: 'Prepared for your review — please verify all information.',
          fontRef: 'body',
          size: 8,
          color: '#A8B8E8',
          align: 'left',
        },
        // Gold accent line under header
        {
          id: 'el_accent_line',
          type: 'line',
          x1: 36, y1: 112, x2: 576, y2: 112,
          stroke: '#C9A227',
          width: 2.5,
        },

        // ── SECTION: CLIENT INFORMATION ──────────────────────────────
        {
          id: 'el_sec_client_label',
          type: 'text',
          x: 36, y: 124, w: 200, h: 14,
          content: 'CLIENT INFORMATION',
          fontRef: 'body',
          size: 8,
          color: '#1B2A6B',
          weight: 'bold',
        },

        // Row: Client Name (label + field)
        {
          id: 'el_lbl_client_name',
          type: 'text',
          x: 36, y: 144, w: 120, h: 13,
          content: 'Client Name',
          fontRef: 'body',
          size: 9,
          color: '#6B7280',
        },
        {
          id: 'el_field_client_name',
          type: 'field',
          fieldType: 'text',
          name: 'client_name',
          x: 36, y: 160, w: 254, h: 32,
          label: 'Client Name',
          placeholder: 'Full legal name',
          required: true,
          boxStyle: { fill: '#EEF2F9', stroke: '#D5DEEC', radius: 8, innerHighlight: true },
          widgetStyle: { fontRef: 'body', size: 11, color: '#1B2A6B', align: 'left', padding: 8 },
        },

        // Row: Policy # (same row, right side)
        {
          id: 'el_lbl_policy_no',
          type: 'text',
          x: 302, y: 144, w: 120, h: 13,
          content: 'Policy #',
          fontRef: 'body',
          size: 9,
          color: '#6B7280',
        },
        {
          id: 'el_field_policy_no',
          type: 'field',
          fieldType: 'text',
          name: 'policy_number',
          x: 302, y: 160, w: 274, h: 32,
          label: 'Policy Number',
          placeholder: 'e.g. POL-001234',
          boxStyle: { fill: '#EEF2F9', stroke: '#D5DEEC', radius: 8, innerHighlight: true },
          widgetStyle: { fontRef: 'body', size: 11, color: '#1B2A6B', align: 'left', padding: 8 },
        },

        // Row: Effective Date (left) + Agency (right)
        {
          id: 'el_lbl_eff_date',
          type: 'text',
          x: 36, y: 202, w: 120, h: 13,
          content: 'Effective Date',
          fontRef: 'body',
          size: 9,
          color: '#6B7280',
        },
        {
          id: 'el_field_eff_date',
          type: 'field',
          fieldType: 'date',
          name: 'effective_date',
          x: 36, y: 218, w: 170, h: 32,
          label: 'Effective Date',
          placeholder: 'MM/DD/YYYY',
          boxStyle: { fill: '#FBF4DD', stroke: '#D5DEEC', radius: 8 },
          widgetStyle: { fontRef: 'body', size: 11, color: '#1B2A6B', align: 'left', padding: 8 },
        },
        {
          id: 'el_lbl_agency',
          type: 'text',
          x: 218, y: 202, w: 120, h: 13,
          content: 'Agency',
          fontRef: 'body',
          size: 9,
          color: '#6B7280',
        },
        {
          id: 'el_field_agency',
          type: 'field',
          fieldType: 'text',
          name: 'agency_name',
          x: 218, y: 218, w: 174, h: 32,
          label: 'Agency',
          placeholder: 'Agency name',
          boxStyle: { fill: '#EEF2F9', stroke: '#D5DEEC', radius: 8 },
          widgetStyle: { fontRef: 'body', size: 11, color: '#1B2A6B', align: 'left', padding: 8 },
        },
        {
          id: 'el_lbl_agent',
          type: 'text',
          x: 404, y: 202, w: 100, h: 13,
          content: 'Agent',
          fontRef: 'body',
          size: 9,
          color: '#6B7280',
        },
        {
          id: 'el_field_agent',
          type: 'field',
          fieldType: 'text',
          name: 'agent_name',
          x: 404, y: 218, w: 172, h: 32,
          label: 'Agent Name',
          placeholder: 'Agent name',
          boxStyle: { fill: '#EEF2F9', stroke: '#D5DEEC', radius: 8 },
          widgetStyle: { fontRef: 'body', size: 11, color: '#1B2A6B', align: 'left', padding: 8 },
        },

        // Divider
        {
          id: 'el_div_2',
          type: 'line',
          x1: 36, y1: 263, x2: 576, y2: 263,
          stroke: '#D5DEEC',
          width: 1,
        },

        // ── SECTION: POLICY SUMMARY TABLE ────────────────────────────
        {
          id: 'el_sec_policy_label',
          type: 'text',
          x: 36, y: 273, w: 200, h: 14,
          content: 'POLICY SUMMARY',
          fontRef: 'body',
          size: 8,
          color: '#1B2A6B',
          weight: 'bold',
        },

        // Table header row (navy bg)
        {
          id: 'el_tbl_hdr_bg',
          type: 'rect',
          x: 36, y: 291, w: 540, h: 26,
          fill: '#1B2A6B',
          radius: 4,
        },
        {
          id: 'el_tbl_hdr_col1',
          type: 'text',
          x: 44, y: 297, w: 222, h: 14,
          content: 'Policy / Coverage Type',
          fontRef: 'body',
          size: 9,
          color: '#FFFFFF',
          weight: 'bold',
        },
        {
          id: 'el_tbl_hdr_col2',
          type: 'text',
          x: 272, y: 297, w: 138, h: 14,
          content: 'Effective Date',
          fontRef: 'body',
          size: 9,
          color: '#FFFFFF',
          weight: 'bold',
        },
        {
          id: 'el_tbl_hdr_col3',
          type: 'text',
          x: 416, y: 297, w: 152, h: 14,
          content: 'Carrier',
          fontRef: 'body',
          size: 9,
          color: '#FFFFFF',
          weight: 'bold',
        },

        // Table row 1 (light bg)
        {
          id: 'el_row1_bg',
          type: 'rect',
          x: 36, y: 321, w: 540, h: 36,
          fill: '#F8FAFC',
          stroke: '#D5DEEC',
          strokeWidth: 0.5,
        },
        {
          id: 'el_field_policy1',
          type: 'field',
          fieldType: 'text',
          name: 'policy_type_1',
          x: 40, y: 325, w: 226, h: 28,
          placeholder: 'e.g. Commercial Auto',
          boxStyle: { fill: '#EEF2F9', stroke: '#D5DEEC', radius: 4 },
          widgetStyle: { fontRef: 'body', size: 10, color: '#1B2A6B', padding: 6 },
        },
        {
          id: 'el_field_effdate1',
          type: 'field',
          fieldType: 'date',
          name: 'policy_eff_1',
          x: 270, y: 325, w: 140, h: 28,
          placeholder: 'MM/DD/YYYY',
          boxStyle: { fill: '#FBF4DD', stroke: '#D5DEEC', radius: 4 },
          widgetStyle: { fontRef: 'body', size: 10, color: '#1B2A6B', padding: 6 },
        },
        {
          id: 'el_field_carrier1',
          type: 'field',
          fieldType: 'text',
          name: 'carrier_1',
          x: 414, y: 325, w: 158, h: 28,
          placeholder: 'Carrier name',
          boxStyle: { fill: '#EEF2F9', stroke: '#D5DEEC', radius: 4 },
          widgetStyle: { fontRef: 'body', size: 10, color: '#1B2A6B', padding: 6 },
        },

        // Table row 2 (white bg)
        {
          id: 'el_row2_bg',
          type: 'rect',
          x: 36, y: 361, w: 540, h: 36,
          fill: '#FFFFFF',
          stroke: '#D5DEEC',
          strokeWidth: 0.5,
        },
        {
          id: 'el_field_policy2',
          type: 'field',
          fieldType: 'text',
          name: 'policy_type_2',
          x: 40, y: 365, w: 226, h: 28,
          placeholder: 'e.g. General Liability',
          boxStyle: { fill: '#EEF2F9', stroke: '#D5DEEC', radius: 4 },
          widgetStyle: { fontRef: 'body', size: 10, color: '#1B2A6B', padding: 6 },
        },
        {
          id: 'el_field_effdate2',
          type: 'field',
          fieldType: 'date',
          name: 'policy_eff_2',
          x: 270, y: 365, w: 140, h: 28,
          placeholder: 'MM/DD/YYYY',
          boxStyle: { fill: '#FBF4DD', stroke: '#D5DEEC', radius: 4 },
          widgetStyle: { fontRef: 'body', size: 10, color: '#1B2A6B', padding: 6 },
        },
        {
          id: 'el_field_carrier2',
          type: 'field',
          fieldType: 'text',
          name: 'carrier_2',
          x: 414, y: 365, w: 158, h: 28,
          placeholder: 'Carrier name',
          boxStyle: { fill: '#EEF2F9', stroke: '#D5DEEC', radius: 4 },
          widgetStyle: { fontRef: 'body', size: 10, color: '#1B2A6B', padding: 6 },
        },

        // Table row 3
        {
          id: 'el_row3_bg',
          type: 'rect',
          x: 36, y: 401, w: 540, h: 36,
          fill: '#F8FAFC',
          stroke: '#D5DEEC',
          strokeWidth: 0.5,
        },
        {
          id: 'el_field_policy3',
          type: 'field',
          fieldType: 'text',
          name: 'policy_type_3',
          x: 40, y: 405, w: 226, h: 28,
          placeholder: 'e.g. Workers Comp',
          boxStyle: { fill: '#EEF2F9', stroke: '#D5DEEC', radius: 4 },
          widgetStyle: { fontRef: 'body', size: 10, color: '#1B2A6B', padding: 6 },
        },
        {
          id: 'el_field_effdate3',
          type: 'field',
          fieldType: 'date',
          name: 'policy_eff_3',
          x: 270, y: 405, w: 140, h: 28,
          placeholder: 'MM/DD/YYYY',
          boxStyle: { fill: '#FBF4DD', stroke: '#D5DEEC', radius: 4 },
          widgetStyle: { fontRef: 'body', size: 10, color: '#1B2A6B', padding: 6 },
        },
        {
          id: 'el_field_carrier3',
          type: 'field',
          fieldType: 'text',
          name: 'carrier_3',
          x: 414, y: 405, w: 158, h: 28,
          placeholder: 'Carrier name',
          boxStyle: { fill: '#EEF2F9', stroke: '#D5DEEC', radius: 4 },
          widgetStyle: { fontRef: 'body', size: 10, color: '#1B2A6B', padding: 6 },
        },

        // Bottom table border
        {
          id: 'el_tbl_bottom_border',
          type: 'line',
          x1: 36, y1: 437, x2: 576, y2: 437,
          stroke: '#D5DEEC',
          width: 1,
        },

        // ── FOOTER DISCLAIMER ─────────────────────────────────────────
        {
          id: 'el_footer_div',
          type: 'line',
          x1: 36, y1: 750, x2: 576, y2: 750,
          stroke: '#D5DEEC',
          width: 0.5,
        },
        {
          id: 'el_footer_text',
          type: 'text',
          x: 36, y: 756, w: 540, h: 24,
          content:
            'This document is for informational purposes only. Coverage is subject to actual policy terms. Navion Insurance Group.',
          fontRef: 'body',
          size: 7,
          color: '#9CA3AF',
          align: 'center',
        },
      ],
    },
  ],
};
